on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.MENTORINGWEBAPPCONNECTION }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./main.bicep
        parameters: 'vnetName=mainvnetworktest1 vnetAddressSpace=10.1.0.0/16 snetAppSvcAddressPrefix=10.1.2.0/24 snetPrivateLinkAddressPrefix=10.1.1.0/24'
        failOnStdErr: false
